import React from "react";
import { Reveal, MeshBackground } from "../components/UIComponents";

const Terms = () => {
  return (
    /* MAIN SECTION WRAPPER 
       'min-h-screen' ensures the background covers the full page height.
       'overflow-hidden' is necessary to clip the MeshBackground elements.
    */
    <section className="relative py-20 md:py-32 bg-slate-50 dark:bg-slate-950 min-h-screen transition-colors overflow-hidden">
      {/* Background decoration: Positioned absolute to sit behind content */}
      <div className="absolute inset-0 opacity-40 pointer-events-none">
        <MeshBackground />
      </div>

      {/* CONTENT WRAPPER: relative z-10 brings this above the background decoration */}
      <div className="max-w-4xl mx-auto px-6 relative z-10">
        <Reveal>
          <h1 className="text-4xl md:text-5xl font-black text-slate-900 dark:text-white mb-8 tracking-tight">
            Terms of Use
          </h1>
        </Reveal>

        {/* MAIN CONTENT CARD 
            'bg-white/80' with 'backdrop-blur-xl' creates the glassmorphism effect.
            'max-w-none' allows the container to use the full width of its parent (max-w-4xl).
        */}
        <div className="bg-white/80 dark:bg-slate-900/80 backdrop-blur-xl rounded-[2rem] p-8 md:p-12 border border-slate-200/50 shadow-2xl max-w-none">
          
          {/* DYNAMIC DATE: Automatically sets the date to the current user's local date format */}
          <p className="text-slate-500 dark:text-slate-400 mb-8 font-mono text-sm uppercase tracking-widest">
            Effective Date: {new Date().toLocaleDateString()}
          </p>

          {/* DOCUMENT BODY
              'space-y-8' creates consistent vertical gaps between sections.
              'text-justify' ensures professional alignment on both left and right edges.
          */}
          <div className="space-y-8 text-slate-600 dark:text-slate-400 leading-relaxed text-justify">
            <section>
              <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-3">1. Acceptance of Terms</h3>
              <p>
                By accessing this portal and submitting an enquiry, you agree to be bound by these Terms of Use and all applicable laws and regulations.
              </p>
            </section>

            <section>
              <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-3">2. Quote Requests (Enquiries)</h3>
              <p>
                The "Enquiry Record" generated by this site is a preliminary request for information. It does not constitute a formal contract, a final price guarantee, or an obligation for us to provide services until a formal commercial agreement is signed.
              </p>
            </section>

            <section>
              <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-3">3. User Conduct & Uploads</h3>
              <p>
                Users are prohibited from uploading files that contain viruses, malware, or any content that violates third-party intellectual property rights. We reserve the right to delete any submission that is deemed harmful or inappropriate.
              </p>
            </section>

            <section>
              <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-3">4. Limitation of Liability</h3>
              <p>
                We provide this digital portal "as is." While we strive for 100% uptime and data accuracy, we are not liable for any technical errors, data loss, or damages resulting from the use of this website.
              </p>
            </section>

            <section>
              <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-3">5. Intellectual Property</h3>
              <p>
                All content, including the design, logos, and interactive elements of this portal, are the property of our company and protected by international copyright laws.
              </p>
            </section>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Terms;